### ISSUE TITLE
considerations for other deployment types (bootkube)

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/armada#167]
**Is this a bug report or feature request?** (choose one):

**Python Version** (output of `python --version`): N/A

**Development or Deployment Environment?**: N/A

**Release Tag or Master**: master

**Expected Behavior**: armada would work as documented

**What Actually Happened**: armada fails because of unmounted client certificates

**How to Reproduce the Issue** (as minimally as possible): use the following repo, and then test with armada: https://github.com/v1k0d3n/bootkube-ci

**Any Additional Comments**: 
background: in cases where user-created certificates are issued and called by kubeconfig (typically in `/home/${USER}/.kube/config`, Armada is not going to consider mounting certificates/keys needed.

sample:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/ubuntu/.bootkube/tls/ca.crt
    server: https://45.58.41.236:8443
  name: local
contexts:
- context:
    cluster: local
    user: kubelet
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: kubelet
  user:
    client-certificate: /home/ubuntu/.bootkube/tls/kubelet.crt
    client-key: /home/ubuntu/.bootkube/tls/kubelet.key
```

This creates a problem, as Armada would fail in cases that use certs/keys for users.
