### ISSUE TITLE
feat: pre/post - actions to improve/secure lifecycle

### ISSUE THREAD

**Issue by gardlt** [att-comdev/armada#42]
ARMADA should be able to support arbitrary action inside k8s as part of the workflow (delete/etc)
Pre/post requirements during the chart deployment life cycle, This is not  implemented

```
install:
         no_hooks: false
        upgrade:
          no_hooks: false
          pre:
            delete:
                   - name: keystone-db-sync
                      type: 'job'
                   - name: keystone-db-init
                      type: 'job'
```
